### ISSUE TITLE
superclass mismatch for class Tempfile

### ISSUE THREAD

**Issue by 3wille** [Shopify/bootsnap#122]
Hello,

I am currently trying to upgrade our Rails ``5.1.4`` App from MRI ``1.4.1`` to MRI ``1.5.0``.
When starting the App with bootsnap, I get the following error:

```
/usr/local/opt/rbenv/versions/2.5.0/lib/ruby/2.5.0/tempfile.rb:81:in `<main>': superclass mismatch for class Tempfile (TypeError)
```

It works again after disabling ``load_path_cache``. I already tried deleting the bootsnap cache files in ``tmp/cache``. Have you any idea what might be causing this? Help would be really appreciated and thanks in advance :)

**Comment by 3wille** [comment]
I now found that this error does not occur on CircleCI but still on my OSX machine.

**Comment by ojab** [comment]
Can you please check if https://github.com/Shopify/bootsnap/pull/136 fixes the issue? You can try it with `gem 'bootsnap', github: 'ojab/bootsnap', require: false` in Gemfile.

**Comment by 3wille** [comment]
Hello @ojab , when running your branch, the OSX-``system``-ruby returns a ``LoadError: No such file to load``on requiring a file that is located at ``app/lib``. The rbenv-ruby returns the same error, then segfaults.

**Comment by burke** [comment]
I bet this is fixed in version 1.2.0.pre, please let me know whether that fixes this issue or not.

**Comment by rafaelfranca** [comment]
@burke should not we have a tag for that release in the repository?

**Comment by burke** [comment]
Yes, done.

**Comment by 3wille** [comment]
Hello @burke, after setting ``gem "bootsnap", "1.2.0.pre"`` in the gemfile and running ``bundle``, I still get the same error.

**Comment by burke** [comment]
Can you check if 1.3.0 fixes this?

**Comment by askehansen** [comment]
@burke it fixed the issue for me
