### ISSUE TITLE
Cannot load local libraries in booting process(rails 4.2.5 / ruby 2.5.0)

### ISSUE THREAD

**Issue by kirikak2** [Shopify/bootsnap#137]
Hi Team.
Thanks for providing great tool. My app boot 2x faster than before!

I have a problem which cannot load local libs to apply bootsnap gem.

This is sample code to occur same problem.
https://github.com/kirikak2/apply_bootsnap_rails

I located `test_lib.rb` in `lib/` dir. and call from `config/initializers/boot_test_lib.rb`
so It returned as follows.

```
$ rails c
/Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require': cannot load such file -- test_lib (LoadError)
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /Users/maki/projects/rails_4_2_8/config/initializers/boot_test_lib.rb:1:in `<main>'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:415:in `call'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
        from /Users/maki/projects/rails_4_2_8/config/environment.rb:5:in `<main>'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from -e:1:in `<main>'
m
```

This problem is occured only booting process. If I remove `config/initializers/boot_test_lib.rb`, execute `rails c` and `require 'test_lib'`, It successed.

```
$ rails c
Running via Spring preloader in process 45829
Loading development environment (Rails 4.2.8)
irb(main):001:0> require 'test_lib'
Hello
=> true
```

It also occured calling rspec. (need to remove `config/initializers/boot_test_lib.rb`)
It could not find `spec_helper`.

```
$ bundle exec bin/rspec spec
Running via Spring preloader in process 43047
Traceback (most recent call last):
        24: from -e:1:in `<main>'
        23: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        22: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        21: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
        20: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
        19: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        18: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
        17: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
        16: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
        15: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<main>'
        14: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
        13: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
        12: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
        11: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
        10: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:21:in `configure'
         9: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
         8: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `each'
         7: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
         6: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `requires='
         5: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `each'
         4: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `block in requires='
         3: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
         2: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
         1: from /Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/Users/maki/.anyenv/envs/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require': cannot load such file -- spec_helper (LoadError)
```

It seems to occured only via `bin/rspec`.
When I avoid using `bin/rspec`. It successed.

```
$ bundle exec rspec spec
Running via Spring preloader in process 46043
**.***********.............

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) TestsController GET #index returns a success response
     # Add a hash of attributes valid for your model
     # ./spec/controllers/tests_controller_spec.rb:45

  2) TestsController GET #show returns a success response
     # Add a hash of attributes valid for your model
     # ./spec/controllers/tests_controller_spec.rb:53

  ....
```

Currently, I found workaround in this problem.

`lib/bootsnap/load_path_cache/core_ext/kernel_require.rb`

```ruby
  def require(path)
    if resolved = Bootsnap::LoadPathCache.load_path_cache.find(path)
      require_without_cache(resolved)
    else
      begin
        require_without_cache(path)
      rescue => exception 
        raise Bootsnap::LoadPathCache::CoreExt.make_load_error(path)
      end
    end
  rescue Bootsnap::LoadPathCache::ReturnFalse
    return false
  rescue Bootsnap::LoadPathCache::FallbackScan
    require_without_cache(path)
  end
```

I think this is not good idea.
If you have any good one. Please note me.

Thanks.

**Comment by paulvt** [comment]
This problem also occurs when a gem/library is present on the system (outside the bundle). For example, the `multi_json` gem loads the `oj` library which in turn tries to require `oj/easy_hash` which it cannot seem to find in the cache and it then fails immediately. The workaround suggested above fixes this by doing a second attempt of requiring the file directly.
This problem started occurring for us when upgrading from Ubuntu 16.04 (Xenial) to 17.10 (Artful).

**Comment by paulvt** [comment]
The following diff is an update that applies to bootsnap 1.2.0:

```diff
--- a/bundle/ruby/2.3.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb	2018-03-26 11:48:55.666483341 +0200
+++ b/bundle/ruby/2.3.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb	2018-03-26 11:50:23.115857126 +0200
@@ -27,7 +27,11 @@
       return require_with_bootsnap_lfi(path, resolved)
     end
 
+    begin
+      require_without_bootsnap(path)
+    rescue LoadError
     raise Bootsnap::LoadPathCache::CoreExt.make_load_error(path)
+    end
   rescue Bootsnap::LoadPathCache::ReturnFalse
     return false
   rescue Bootsnap::LoadPathCache::FallbackScan
@@ -45,7 +49,11 @@
       return load_without_bootsnap(relative, wrap)
     end
 
+    begin
+      load_without_bootsnap(path)
+    rescue LoadError
     raise Bootsnap::LoadPathCache::CoreExt.make_load_error(path)
+    end
   rescue Bootsnap::LoadPathCache::ReturnFalse
     return false
   rescue Bootsnap::LoadPathCache::FallbackScan
@@ -69,7 +77,11 @@
       return require_with_bootsnap_lfi(path, resolved)
     end
 
+    begin
+      require_without_bootsnap(path)
+    rescue LoadError
     raise Bootsnap::LoadPathCache::CoreExt.make_load_error(path)
+    end
   rescue Bootsnap::LoadPathCache::ReturnFalse
     return false
   rescue Bootsnap::LoadPathCache::FallbackScan
@@ -87,7 +99,11 @@
       return load_without_bootsnap(relative, wrap)
     end
 
+    begin
+      load_without_bootsnap(path)
+    rescue LoadError
     raise Bootsnap::LoadPathCache::CoreExt.make_load_error(path)
+    end
   rescue Bootsnap::LoadPathCache::ReturnFalse
     return false
   rescue Bootsnap::LoadPathCache::FallbackScan
```

**Comment by jules2689** [comment]
@burke do you have any ideas on this one?

**Comment by burke** [comment]
It's probably fixed in 1.3.0

**Comment by jules2689** [comment]
@kirikak2 can you try using 1.3.0 and check if that fixes it? sorry for the delay in response!

**Comment by kirikak2** [comment]
@burke @jules2689 Thanks! I will try in next week, and report result.

**Comment by Spone** [comment]
I have the same issue with bootsnap 1.3.0 when linking a local gem in my Gemfile, with:

    gem 'my_gem', path: "~/projects/my_gem"

**Comment by bak1an** [comment]
I am seeing similar issue with 1.3.0 (load error during rspec and no error when `require` later after boot).

Some sort of @paulvt's patch looks sane as a fix to me. It is a cache after all and it kind of makes sense to try loading file the old way before raising in case it is not resolved via cache.

<hr/>

I'll spend some extra time to find out why the path is not in cache in my case though. Looks like something (rspec?) changing LOAD_PATH after initial cache was built.

What if in https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/load_path_cache/cache.rb#L156 we also check for `@path_obj` changes and consider cache stale in case it is not the same as before?

Btw, is it safe/required to `map!` over `$LOAD_PATH`?

**Comment by burke** [comment]
We've fixed a bunch of issues that seem related to this since the time that this was last-commented-on, so I'm going to close, but feel free to reopen if I'm wrong.

It is safe to `map!` over `$LOAD_PATH`, yeah, our change observer should handle that.
