### ISSUE TITLE
IDE debugging of apps on Rails 5.2 broken

### ISSUE THREAD

**Issue by grumBit** [Shopify/bootsnap#168]
### Steps to reproduce
See attached development_machine_installation.txt, then follow steps in expected behaviour section
[development_machine_installation.txt](https://github.com/Shopify/bootsnap/files/1953629/development_machine_installation.txt)

### Expected behavior
In IDE;
- add break point to first line of [app root]/ config/application.rb;
        require_relative 'boot'
- start debug.
- debugger should stop at breakpoint

### Actual behavior
- debugger continues without stopping
- NB: Any breakpoint further into execution of the Rails app fails to halt execution.

### Work around;
Edit [app root]/ config/boot.rb
Comment out line;
- require 'bootsnap/setup'

Debugging now works throughout app as expected.

### Notes;
Looking at https://github.com/Shopify/bootsnap/issues/93, I believe this problem occurs due a combination of the following;
- new Ruby 2.5 feature "Remove `trace` instructions" (https://bugs.ruby-lang.org/issues/14104)
- Rails 5.2 inclusion of bootsnap gem

NB: The same problem is occurring in a number of IDE's;
- Jetbrains;  https://youtrack.jetbrains.com/issue/RUBY-20684
- RubyMine; https://github.com/ruby-debug/ruby-debug-ide/issues/139
- VSCode; https://github.com/rubyide/vscode-ruby/issues/337

I believe this is a Ruby + bootsnap issue rather than bootsnap itself.  However, I'm guessing the "best" place to fix it would be in bootsnap.

Also, I wanted to log the problem with a clear title so other Rails developers using IDE's will know what is going on, rather than spending time on searching for answers

(Apologies if my shotgun approach to submitting this issue on multiple repos is poor-form.  I'm new to open-source development)

### System configuration
- `vscode-ruby` version: 0.18.0
- Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
- Rails version: 5.2.0
- ruby-debug-ide version: 0.6.1
- debase version: 0.2.2
- VS Code version: 1.22.2 (1.22.2)
- Operating System: macOS 10.13.4 (17E199)
- Hardware (optional): MacBook Pro (13-inch, Mid 2012) & MacBook (13-inch, Mid 2010)

**Comment by tzmfreedom** [comment]
Bootsnap use `RubyVM::InstructionSequence.load_from_binary` to load other file quickly, and almost all debugger use `TracePoint` feature.

I guess `TracePoint` hook doesn't work when you load file with `RubyVM::InstructionSequenc.load_from_binary` on Ruby 2.5.
So I post the issue to Ruby Issue Tracking System.
https://bugs.ruby-lang.org/issues/14702

If my guess is correct, you may wait updated Ruby or stop bootsnap compile cache iseq feature like the following.
```ruby
require 'bootsnap'

env = ENV['RAILS_ENV'] || 'development'

Bootsnap.setup(
  cache_dir: 'tmp/cache',
  development_mode: env == 'development',
  load_path_cache: true,
  autoload_paths_cache: true,
  disable_trace: true,
  compile_cache_iseq: false,
  compile_cache_yaml: true
)
```

**Comment by rafaelfranca** [comment]
Fixed by https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/64514/diff. It will be present in next Ruby 2.5. Thanks @ko1!

**Comment by pedrofurtado** [comment]
Also for reference: https://github.com/ruby/ruby/commit/c1034574aa7e6f47843b5533411c75d8196b29d8

**Comment by nedgar** [comment]
@pedrofurtado while perhaps not the exact same issue, if I invoke byebug via `debugger` in the code, I find the `n` is often skipping further ahead than one line. Do you see this too?
This is in core, running `ruby 2.5.3p105 (2018-10-18 revision 65156) `

**Comment by pedrofurtado** [comment]
@nedgar Are you using `byebug` + `pry-byebug` ( https://github.com/deivid-rodriguez/pry-byebug )? If so, I did not test this scenario, because I only use `byebug` standalone. Try to use only `byebug` (without `pry-byebug`) and check if the error occurs. If not, it could a bug in `pry-byebug`, and is better to open a issue in repo of `pry-byebug`. Ping me and @deivid-rodriguez if necessary, to help you to provide a solution or some workaround. :+1:

**Comment by nedgar** [comment]
@pedrofurtado I was using both (`pre-byebug` is include in core's Gemfile). I removed it, and also disabled BootSnap in `boot.rb`, then ran `dev down` and `dev up`. This problem still occurs.
Here's an example. 

After stepping in a bit, using `n` to run the following assignment statements one at a time works as expected:
```ruby
[159, 168] in /Users/nedgar/src/github.com/Shopify/shopify/components/launch/app/models/account_setup.rb
   159:   end
   160: 
   161:   private
   162: 
   163:   def save_shop(shop)
=> 164:     shop.skip_payment_rates_rebuild = true
   165:     shop.editing_shop = true
   166:     shop.attributes = shop_attributes(shop)
   167:     update_signup_settings(shop)
   168: 
(byebug) n

[160, 169] in /Users/nedgar/src/github.com/Shopify/shopify/components/launch/app/models/account_setup.rb
   160: 
   161:   private
   162: 
   163:   def save_shop(shop)
   164:     shop.skip_payment_rates_rebuild = true
=> 165:     shop.editing_shop = true
   166:     shop.attributes = shop_attributes(shop)
   167:     update_signup_settings(shop)
   168: 
   169:     saved = if shop.valid?
(byebug) n

[161, 170] in /Users/nedgar/src/github.com/Shopify/shopify/components/launch/app/models/account_setup.rb
   161:   private
   162: 
   163:   def save_shop(shop)
   164:     shop.skip_payment_rates_rebuild = true
   165:     shop.editing_shop = true
=> 166:     shop.attributes = shop_attributes(shop)
   167:     update_signup_settings(shop)
   168: 
   169:     saved = if shop.valid?
   170:       questions.update_shop(shop)
(byebug) n

[162, 171] in /Users/nedgar/src/github.com/Shopify/shopify/components/launch/app/models/account_setup.rb
   162: 
   163:   def save_shop(shop)
   164:     shop.skip_payment_rates_rebuild = true
   165:     shop.editing_shop = true
   166:     shop.attributes = shop_attributes(shop)
=> 167:     update_signup_settings(shop)
   168: 
   169:     saved = if shop.valid?
   170:       questions.update_shop(shop)
   171:       shop.save
```
But here, with the method invocation to `update_signup_settings` about to be run, `n` acts like `c`: rather than stopping at line 169, it continues then stops at my next `debugger` statement, higher up in `account_setup`:

```ruby
(byebug) n

[122, 131] in /Users/nedgar/src/github.com/Shopify/shopify/components/launch/app/models/account_setup.rb
   122:       return false
   123:     end
   124: 
   125:     saved = save_shop(shop)
   126:     debugger
=> 127:     if saved
   128:       configure_shop(shop)
   129:       debugger
   130:       setup_completed(shop)
   131:       debugger
(byebug) 
```

**Comment by nedgar** [comment]
Our `byebug` was at the last release: 10.0.2. I switched to HEAD with:
```ruby
group :development, :debug, :test, :staging do
  gem 'byebug', github: 'deivid-rodriguez/byebug'
end
```
and again ran `dev down` and `dev up`. The problem remains.

**Comment by nedgar** [comment]
Thanks, for confirming it's still an issue at Ruby level, @deivid-rodriguez. I'll see what response there is tomorrow and whether the issue gets reopened.

**Comment by XrXr** [comment]
@nedgar The "n skipping over too many lines" issue is not fixed by my patch. (https://bugs.ruby-lang.org/issues/15270). I suspect it's another MRI issue, but I haven't had time to look into it yet.

**Comment by deivid-rodriguez** [comment]
Thanks for the input @XrXr, and for the work you've been doing :muscle:!

**Comment by Whelliyams** [comment]
i had a bootsnap issue and whenever i deleted the temp/cache/boot sometin file it loads just once and when that file is generated again it repeats the same tin so i totally commented out all that has to do with bootsnap now i wanna know if there is any problem or side effects with that?
